server:
  port: 9900
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shiro-test?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123
  thymeleaf:
     cache: false #热部署文件，页面不产生缓存，及时更新
# 配置通用mapper 将原来写入类中的参数 配置到这里
mybatis:
  type-aliases-package: com.zhanghui.entity #实体类的包所在
  mapper-locations: classpath:mapper/*.xml #mapper类对应的mapper.xml
  mappers: com.zhanghui.MyMapper #mapper的父类  自己写的那个通用mapper
  identity: MYSQL #
  table:
    auto: update
  model:
    pack: com.zhanghui.entity
  database:
    type: mysql 
  configuration:
    map-underscore-to-camel-case: true #开启驼峰命名法  
     
#分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql